version: "3.8"

services:
  server:
    build: .
    depends_on:
      - mongodb
      - redis
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - backend

  mongodb:
    image: mongo
    ports:
      - "27020:27017"
    volumes:
      - mongodb:/data/db
    networks:
      - backend

  redis:
    image: redis
    ports:
      - "6380:6379"
    networks:
      - backend

networks:
  backend:

volumes:
  mongodb:
